### ISSUE TITLE
Escolhas sobre adaptação do mongoDB

### ISSUE THREAD

**Issue by pie172** [pie172/FATEC_PI_1SEM_2024#4]
Durante a aula Desenvolvimento Web II, tivemos uma discussão sobre uma ou duas tabelas no mongo, junto com o professor e colegas do grupo.

**Comment by orlandosaraivajr** [comment]
Um bom artigo, que faz link com o que conversamos:
https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html 
Ao segregar o service.py do Django, este deve encapsular a forma como o grupo trabalha com o MongoDB
